server:
  port: 8081

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

spring:
  application:
    name: cotacaoapi
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5555/testdb
    username: postgres
    password: postgres
    hikari:
      auto-commit: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: public

opentracing:
  jaeger:
    http-sender:
      url: http://localhost:16686/api/traces

